// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBtF2aXIdNtBAhu2n4_Cr4WUCcsP1zv8M',
    appId: '1:182474522864:web:1d1aa2c0d646a9ef22c235',
    messagingSenderId: '182474522864',
    projectId: 'projectfirebase-5b582',
    authDomain: 'projectfirebase-5b582.firebaseapp.com',
    storageBucket: 'projectfirebase-5b582.firebasestorage.app',
    measurementId: 'G-RH16G7G7T5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1u-j6VjJ9jEcDgJmbvoMqIYT2q2jxc48',
    appId: '1:182474522864:android:cb48f333c46bbb8822c235',
    messagingSenderId: '182474522864',
    projectId: 'projectfirebase-5b582',
    storageBucket: 'projectfirebase-5b582.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmqCT4ZTkXY0Ll0JwAU83dLx-K6bWV2Bg',
    appId: '1:182474522864:web:f905a48252da059922c235',
    messagingSenderId: '182474522864',
    projectId: 'projectfirebase-5b582',
    authDomain: 'projectfirebase-5b582.firebaseapp.com',
    storageBucket: 'projectfirebase-5b582.firebasestorage.app',
    measurementId: 'G-3Y4XK4XT9M',
  );
}
